### ISSUE TITLE
Access properties like `styles['test']` 

### ISSUE THREAD

**Issue by PodaruDragos** [clinyong/vscode-css-modules#61]
Is there any plan to support accessing styles like `styles['test']`  ?

```
styles.test;
string | undefined
Property 'test' comes from an index signature, so it must be accessed with ['test'].ts(4111)
```

this check is coming from `"noPropertyAccessFromIndexSignature": true` in `tsconfig`.

**Comment by iChenLei** [comment]
Any idea for this feature ? @clinyong

**Comment by iChenLei** [comment]
@PodaruDragos Hello, I think there isn't a easy solution for your issue. Because vscode-css-modules is not a typechecker, We don't known whenever to auto complete `.test` or `['test']` . We only check if property is kebab-case or not and then auto complete your code like `styles['kebab-case']` pr `styles.camelCase` (https://github.com/clinyong/vscode-css-modules/pull/48) , because `styles.kebab-case` is invalid javascript, we must check it and this case is simple(only need check if it is kebab-case).

**Comment by clinyong** [comment]
@iChenLei is right. When you are typing `styles[']`, vscode doesn't trigger our [CompletionProvider](https://github.com/clinyong/vscode-css-modules/blob/master/src/extension.ts#L16). It's hard to do this ourself.

**Comment by PodaruDragos** [comment]
Ok, thanks for clearing this out

**Comment by Viijay-Kr** [comment]
[React CSS Modules](https://marketplace.visualstudio.com/items?itemName=viijay-kr.react-ts-css)

Addresses this very problem . My project has only non camel case selectors and this feature was so needed so I built my own extension with lots of other features too.
I hope it helps

**Comment by cp3hnu** [comment]
> [React CSS Modules](https://marketplace.visualstudio.com/items?itemName=viijay-kr.react-ts-css) Addresses this problem .
> 
> My project has only non camel case selectors and this feature was so needed so I built my own extension with lots of other features too. I hope it helps

It's great. It can support BEM methodology very well. I hope that vscode-css-modules can support BEM methodology too.
